### ISSUE TITLE
Scaling 1.25 off

### ISSUE THREAD

**Issue by dirkx** [t-oster/VisiCut#174]
Am trying to find out why visicut is often 1.25 for SVG files generated on the mac (with for example OmniGraffle - which generally display right in other tools).

Simples of examples is below - I'd expected this to be 10x10mm; it shows up as 0.8 or 0.81 depending on the phase of the moon.

Dw.

`<?xml version="1.0"?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xl="http://www.w3.org/1999/xlink" version="1.1">
  <defs/>
  <g stroke="none" stroke-opacity="1" stroke-dasharray="none" fill="none" fill-opacity="1">
    <g>
      <rect x="5mm" y="5mm" width="10mm" height="10mm" stroke="black" stroke-linecap="round" stroke-linejoin="round" stroke-width="1"/>
    </g>
  </g>
</svg>`

**Comment by renebohne** [comment]
I created an SVG file with the rectangle specified by dirkx:
http://hci.rwth-aachen.de/~bohne/simpleRectDPITest.svg

If I open it in Illustrator CS5, the coordinates and dimensions are ok.
In Inkscape, te stroke width leads to (x,y)=(9.5mm,186,5mm) and dimensions (101mm,101mm).

In VisiCut 1.7-98 on Mac OS X, it is imported as (7.857,7.857) with dimensions (80.262 mm,80.262 mm)

**Comment by renebohne** [comment]
If I build from sources (develop branch) and start the build, this version of visicut imports the rect as follows:
(x,y): (14.189 mm, 14.189 mm)
(w,h): (143.579 mm,143.579 mm)

Does the build server use a different version of some libraries (e.g. svgsalamander) than the ones included on github?

**Comment by mgmax** [comment]
another problem is if one edits an illustrator-svg with inkscape. In this case VIsiCut should warn and ask "Did you last edit this SVG with Inkscape or Illustrator?", instead of assuming that it is an Illustrator-SVG and making the scaling wrong.

**Comment by peteruithoven** [comment]
Let's only show warnings when where quite sure we can't figure this out using meta data in the file?

**Comment by t-oster** [comment]
well... that seems to be a tricky issue. And a brilliant use-case for JUnitTests http://www.vogella.com/tutorials/JUnit/article.html. @renebohne don't you have some students, who can create a nice set of example files together with a unit test which imports them and compares the expected dimensions to the imported ones? Then another group of your students (tm) could try to fix the issue ;)

**Comment by renebohne** [comment]
sorry, no new students at the moment... next opportunity will be in April... too late ;) 
I had some deeper looks into the problem and now I think that svgsalamander does not parse units correctly. Need to debug into svgsalamander... but not this week.

1.7-102 still imports like 1.7-98:  (7.857,7.857) with dimensions (80.262 mm,80.262 mm)
although my version (when I compile on my machine) gives different values... different libraries on the build server and on github?

**Comment by t-oster** [comment]
The build server uses a clean checkout from github. It may be a different JDK-Version to blame. The server uses "jdk7-openjdk 7.u71_2.5.3-1". Maybe you use jdk6, jdk8 or the oracle version?

**Comment by dirkx** [comment]
> If I build from sources (develop branch) and start the build, this version of visicut imports the rect as follows:
> (x,y): (14.189 mm, 14.189 mm)
> (w,h): (143.579 mm,143.579 mm)
> 
> Does the build server use a different version of some libraries (e.g. svgsalamander) than the ones included on github?
> 
So that suggest two issues - a JDK related rounding/calculation error _AND_ a 1.41/7.x factor wrong (close to sqrt(2)) in the conversion itself.

Dw.

**Comment by mgmax** [comment]
something seems to have changed. Importing http://hci.rwth-aachen.de/~bohne/simpleRectDPITest.svg into a self-built current development version (OpenJDK7) shows a width of 10.7cm, which is still not correct.

**Comment by jnweiger** [comment]
Are we using https://github.com/blackears/svgSalamander/blob/master/svg-core/src/main/java/com/kitfox/svg/xml/StyleAttribute.java#L175 ?

It should say 
<pre>
final float inchesPerCm = .3937008f;
</pre>
But that is only a small error.

**Comment by mgmax** [comment]
I suppose multiple bugs are mixed up here.

1. Some programs use 72 dpi instead of 90 or 96dpi.
@dirkx Please provide one example file (with a black filled 100x100mm rectangle) for each program that does not work, so we can add a workaround for each if this is the case. I cannot see any example files in your first post. Github doesn't support attaching SVGs, so you need to upload them somewhere (pastebin etc.) and post the link.

2. A stroke width (in pixels) was not correctly accounted for in the bounding box calculation - fixed by #410

3. Width in absolute units (mm, cm, in) is wrong
Test case (100x100mm black filled, no stroke): https://gist.githubusercontent.com/mgmax/ffa0269ce40c39491d6be08ccb1dbd9a/raw/336ac2fa5ed44783acad4de146322410274a9387/100x100mm-filled-rectangle.svg


I am quite sure the two reasons for 3. are the following:

3a. the slightly incorrect incherPerCm factor as stated by @jnweiger 

3b. svgSalamander uses the screen DPI for converting absolute units instead of VisiCut's internal value `svgResolution = SVGImporter.determineResolution(...)`.
This causes a scaling factor of `(screenDPI / svgResolution)`. svgResolution is usually 90 except for the Illustrator and Inkscape >= 0.92 workarounds.

https://github.com/blackears/svgSalamander/blob/master/svg-core/src/main/java/com/kitfox/svg/xml/StyleAttribute.java#L168

For me (96 dpi screen according to ` xdpyinfo | grep dots`), the width is too large by the factor bb.width/bb.height=1.0663935337626669
This factor equals 96/90*.3936/.3937008=1.0663935658754058 plus a small error below 1e-7.

If someone finds the time, the next interesting step would be to get svgSalamander working as a git submodule (just like LibLaserCut) and to see whether patching the source lines for 3a and 3b fixes the problem. Then we will need to add some "svg resolution override" there to pass our `svgResolution`.

**Comment by jnweiger** [comment]
Ah, maybe one additional idea to put users back in control:

* Make the scaling logic in determineResolution() take into account a manual override 
  option from the GUI.

* Have a gui selection
  - (*) automatic DPI from drawing
  - ( ) 72 DPI (Adobe Illustrator)
  - ( ) 90 DPI (old Inkscape)
  - ( ) 96 DPI (CSS Standard)
  - [NNN] DPI (manual override)

**Comment by mgmax** [comment]
That manual override would be very confusing to most users, and not extremely helpful: Inkscape and Illustrator can be autodetected, and newer versions of Inkscape (and AFAIK also illustrator) add the viewBox attribute so that no DPI information is required (and therefore a selection does not make sense). I fear that the effort needed to implement this carefully would be much larger than the benefit, which is only for a few rare cases.

@dirkx  Without example files unfortunately nobody will be able to help you.

**Comment by mgmax** [comment]
Closing, detaching the remaining issue to #556.
