### ISSUE TITLE
OSX 10.9 Mavericks > VisiCut crashes

### ISSUE THREAD

**Issue by puchelaar-amersfoort** [t-oster/VisiCut#183]
Just downloaded VisiCut 1.7-68-g3a18268. I'm running OSX 10.9 Mavericks. After opening VisiCut I tried to import settings (Edit > Settings > Import Settings) by browsing to the *.vcsettings file. I could select the file, but could not click 'open' (greyed out). Then the dreaded spinning beachball appeared, and I had to forcequit VisiCut after a while.
Uninstalled VisiCut, and removed all plist settings, reinstalled, but alas, the problem persisted. Since I wanted to test something without actually lasercutting as well, I forgot about the settings, and just tried to open my *.svg document. Same problem.

Workaround:
It turned out that putting the *.vcsettings file and my *.svg files on my desktop, and the importing/opening them DOES work. Apparently the problem lies in having to go to my downloads folder (default folder; ~user/downloads) or my Google Drive folder. Probably any folder except my desktop.

So... I now know how to keep on working, but IMO it's a bizarre problem...

**Comment by t-oster** [comment]
Does anybody else encounter that issue? should it be but onto the roadmap for 1.8 (#228)?

**Comment by peteruithoven** [comment]
Might be the same problem as #210 ?

**Comment by t-oster** [comment]
don't think so. As I understand, in #210 VisiCut does not run because of java not working. But in this issue, it runs and the UI is loaded, but it locks up by importing.

After re-reading the first post (maybe the author edited it?) I think it now boils down to "VisiCut has issues when importing settings from google-drive folders", which is in my opinion not very important.

@puchelaar-amersfoort: please close the issue if you no longer think it is important, or please explain what needs to be done.

**Comment by puchelaar-amersfoort** [comment]
I have not used Visicut since, so don't know if the issue was Mavericks related (I'm on Yosemite now), or if it happened because of the fact that my files were in Google Drive folders. So, I'll close this issue, and will let you know if I ever run into it again. Sorry for the bother.
