### ISSUE TITLE
Windows installer crash my environment PATH

### ISSUE THREAD

**Issue by mojocorp** [t-oster/VisiCut#194]
Under windows 7, the installer crash the windows PATH environment variable....

**Comment by renebohne** [comment]
Can't we just skip the Winsows Installer? The ZIP version runs fine, right?

**Comment by mgmax** [comment]
No, the windows installer is easier to use, just like you want a nice 
package on Linux. We use it on our Windows machines.

**Comment by t-oster** [comment]
hmm.... don't like the registry... but may be the cleanest windows-like solution. What about a pull-request ?

**Comment by mgmax** [comment]
@t-oster the issue can now be tagged low priority, because since #249  the installer detects the situation and then does not touch PATH anymore.
I don't consider the case of ultra-long PATH important because we support until 1024 and if you go only a little further, you will hit the windows limit of 4096 (at least in the Win7 GUI).

**Comment by mgmax** [comment]
I would suggest closing this issue, as the inkscape plugin runs fine without PATH and VisiCut doesn't destroy the PATH variable anymore if it is too long.

**Comment by t-oster** [comment]
if somebody objects, please reopen
