### ISSUE TITLE
Error Exception: Conversion = "i" (MAC OSX 10.9)

### ISSUE THREAD

**Issue by pastprimitive** [t-oster/VisiCut#195]
When I click execute I get "Error Exception: Conversion = "i"

Thoughts?

**Comment by t-oster** [comment]
I fixed that specific error in LibLaserCut in the smoothie branch. It will be merged to master as soon as it is finished. Since the smoothieboard also supports a serial interface and g-code, the driver may work (with minor modifications) for the lasersaur. So if you are still planning on testing the driver, you should use the smoothieboard driver as a starting point.
