### ISSUE TITLE
Option to disable resize on import.

### ISSUE THREAD

**Issue by thinkl33t** [t-oster/VisiCut#199]
When using inkscape, sometimes visicut decides to scale things arbitrarily.  I have a 300mm x 200mm bed, and a 300mm x 200mm SVG and it still gets scaled for some reason.

It'd be nice to have an option to disable the "your file did not fit within the cutting bed, it has been resized" functionailty, allow things to be dragged outside the confines of the bed, and just crop away anything outside the laser bed area when Execute is pressed.

**Comment by renebohne** [comment]
you can have a look at pull request #230 
it gives the user more information about what happened after import... it does not solve the bug, but at least, you get some numbers. There is also a new "undo" button in the warning dialog since some versions... it reverts all transformations that VisiCut did.

**Comment by mgmax** [comment]
Closing because the bug was mostly fixed by #230 and there was no response by the original submitter.
