### ISSUE TITLE
[Request] Mark Colour

### ISSUE THREAD

**Issue by thinkl33t** [t-oster/VisiCut#216]
It would be nice to have a different colour to separate mark and cut operations, similr to the different colour for engrave.  I've seen users get confused which is which while creating their mapping.

**Comment by t-oster** [comment]
I don't know if I get your question right, but that should be possible already by creating your own mapping and saving it for other users. You can even set it as default mapping in the options.

**Comment by t-oster** [comment]
If you mean a different color in the UI: you can set those in the material properties. Mark-lines are drawn with the "engrave"-color, while cut-lines are drawn with the "cut"-color.

**Comment by peteruithoven** [comment]
Currently a cut and engrave color is set per material. I think @thinkl33t is looking for a overriding color per laserprofile. Because then you can differentiate between a mark (which is usually a *line* profile) and a regular cut profile (which is also a *line* profile). 

Currently when you create a laserprofile you get the question whether it's a Line profile, Raster profile or Raster3D profile. I'm assuming the *Line* profile's get the *cut* color and the *Raster* profiles get the *engrave* color of the currently used material?

**Comment by t-oster** [comment]
On a "line" profile, you can set the checkbox "is cut", which results in the lines being drawn in "cut"-color. There is also a note next to the checkbox describing that.

**Comment by t-oster** [comment]
(you can only find this in the "options->manage laserprofiles" dialog)

**Comment by peteruithoven** [comment]
Ah, nice. So a quick fix would be to uncheck that option in the mark profile.

**Comment by thinkl33t** [comment]
Aha, that solution is perfect, thanks.
