### ISSUE TITLE
Adding marlin driver for VisiCut

### ISSUE THREAD

**Issue by JSilvaGlez** [t-oster/VisiCut#229]
Hello,
My name is Jaime.
Im starting to learn VisiCut source code.
I want add fork marlin driver laser CO2. I need help to start do it.

I hope know about it.

Greats !

**Comment by renebohne** [comment]
Marlin needs GCode. 
What you want to do: fork the libLasercut project 
create a new driver (in drivers directory).

you can have a look at our iModela driver, since it also uses a special GCode version :
IModelaMill.java
and add a new property, just like IModelaProperty.java

Cutting Vector paths will be quite easy. Adding support for (bitmap) raster parts, might be tricky!

**Comment by t-oster** [comment]
First starting point: https://github.com/t-oster/VisiCut/wiki/Development:-Getting-started
Then read the source of this file: https://github.com/t-oster/LibLaserCut/blob/develop/src/com/t_oster/liblasercut/drivers/SampleDriver.java

**Comment by billieblaze** [comment]
I'd like to +1 this and add, that I've been using the buildlog marlin from here: 
https://github.com/TurnkeyTyranny/buildlog-lasercutter-marlin

would love to get visicut running on this.      looked over the iModela and lasersaur, look pretty tweakable.     

Will trade beer for a driver for marlin!  :)

**Comment by quillford** [comment]
@JSilvaGlez did you ever get anywhere with this? I' ve been working on it and have it in an unstable but occasionally working state.

**Comment by quillford** [comment]
This can be closed now. See [this](https://github.com/t-oster/LibLaserCut/blob/smoothieboard/src/com/t_oster/liblasercut/drivers/Marlin.java)

**Comment by t-oster** [comment]
well, @quillford, looks like  @billieblaze owes you a beer
