### ISSUE TITLE
How do I see the code sended to lasercutter ??

### ISSUE THREAD

**Issue by JSilvaGlez** [t-oster/VisiCut#243]
I need study the code sended to lasercutter.
I want learn his functionallity. And will do improves in the future.
I have tried open .plf to read. Its impossible.

Thanks!!

I hope know about it.

Regards

**Comment by peteruithoven** [comment]
What kind of lasercutter do you have? You can enable logging to a file in the lasercutter settings.

**Comment by JSilvaGlez** [comment]
I Have a Laos Laser. I want learn and improve this project.

**Comment by peteruithoven** [comment]
That's always appreciated ;) 
Maybe you can use this:
http://webviewer.laoslaser.org/
It also shows a description on how to enable these output files.

**Comment by JSilvaGlez** [comment]
Thanks !! I found the solve.
Now Im studing it 
;)

**Comment by t-oster** [comment]
Hi. FYI:
- PLF is just a ZIP file containing the source graphic files (svg,png etc.) and some xml files containing VisiCut's settings. You can just rename it to .zip and then open it. It does not contain any information on the lasercutter, nor the code which is sent to it, because that code is generated on the fly once the lasercutter has been selected in VisiCut.
- If you want to know how to control a LAOS-Laser, read the LAOS wiki about simplecode http://redmine.laoslaser.org/projects/laos/wiki/SimpleCode or use the "debug-file" setting in the lasercutter preferences, so every output is also saved as a file
- If you want to know how VisiCut sends information to Lasercutters, have a look at LibLaserCut's drivers: https://github.com/t-oster/LibLaserCut/tree/develop/src/com/t_oster/liblasercut/drivers
- If an issue is solved, please close it.

**Comment by peteruithoven** [comment]
That's very useful information, I added it to the wiki. 
https://github.com/t-oster/VisiCut/wiki/PLF-format
https://github.com/t-oster/VisiCut/wiki/LAOS-Laser-driver

**Comment by JSilvaGlez** [comment]
closed issue #243
