### ISSUE TITLE
Cmd+W on Mac not working like in other apps

### ISSUE THREAD

**Issue by faheus** [t-oster/VisiCut#372]
Cmd+W normally closes the current window without quitting the application, in Visicut it does $something and brakes my workflow.

**Comment by mgmax** [comment]
"$something" is very vague, could you please try to explain it further?

Do you have more than one Visicut window open? Visicut is not designed to be used like that and has a mechanism (singleinstanceport) that tries to prevent multiple instances being open. If you still manage to do so, saving settings will cause trouble because the concurrent instances might overwrite each other's settings on disk with whatever they have cached at startup. Larger work would be neccesary to make it work correctly.

What is Cmd+W supposed to do if there is only one window?

**Comment by pelrun** [comment]
It's not currently one of the accelerators in the MainView, so I think $something == nop. :)

Ctrl/Cmd+W is generally identical to clicking the close window button on the titlebar. For VisiCut, that's the same as Quit.

**Comment by renebohne** [comment]
So what do you expect to happen when you hit Cmd+w? Should it close all items and provide an empty sheet or should it close VisiCut?

**Comment by mgmax** [comment]
Closing because there was no response
