### ISSUE TITLE
Top left 0,0 ref point non configurable

### ISSUE THREAD

**Issue by NEUROF3N** [t-oster/VisiCut#396]
Not sure if this is exactly an issue, or if I should post this here but I will give it a go. For some reason there is no option to move the 0,0 point to any other position than top left. Unfortunately my machines home position and zero point is bottom left. If I have just missed something I do apologise if not, perhaps this could be added as on option. It would be extremely useful.

**Comment by t-oster** [comment]
Hi, at first it would be helpful, if you post your OS, Version and most importantly used Lasercutter.
Here are a few hints:
- There is a brand new option "origin bottom left" in the laserdevice settings, which only affects the measurements in the UI (everything is the measured from bottom instead of from top)
- Many Lasercutter drivers have an option "Filp Y axis" which shall be used if your cuts are inverse
- If you use a Gcode lasercutter you could add custom Gcode like G0 X0 Y0 at the end of every job to make it move to some desired origin.

But you should also decribe what your problem is in detail. Does the head just go the the "wrong" position after each job, or does it affect lasercutting in any way?
