### ISSUE TITLE
Required files to import settings should not contain personnal data or volatile settings

### ISSUE THREAD

**Issue by neomilium** [t-oster/VisiCut#546]
When you want to share your devices, materials and lasercut settings, the file `setttings/settings.xml` is currently required, which was not the case previously.

Unfortunately, this file contains personal data and volatile settings.
This have two side effects:
 * `recentFiles` entry could be a personal data disclosure
 * `windowBounds`, `lastMaterial`, and maybe more, do appears in a `git diff` when you have your shared `visicut-settings` managed through VCS.

IMHO, all entries which are personal and/or volatile are user-defined and should be moved in a dedicated file. This way the new file should be explicitly excluded from import and a recommendation to ignore it in Git could be made in Wiki.

Note: This discussion follow the one started here:
https://github.com/haum/visicut-settings/issues/1#issuecomment-559681125

**Comment by mgmax** [comment]
@t-oster can you please check what's wrong with the download page? The new version isn't showing up, neither is the previous one.

@neomilium 
The issue should be fixed in VisiCut 1.9-12 or newer which should be available for download in the next days.
I updated the Wiki at https://github.com/t-oster/VisiCut/wiki/How-to-add-default-settings-for-your-lab , please test if that works.

**Comment by t-oster** [comment]
@mgmax right now the build and publish process is not triggered by commits. I have to start it manually. Should be uploaded in a few minutes.

**Comment by neomilium** [comment]
Awesome! I will try ASAP. Thanks
